services:
  rustfs:
    image: rustfs/rustfs:1.0.0-beta.1
    container_name: login_s3_rustfs
    restart: always
    env_file:
      - .env
    ports:
      - "9100:9000"
      - "9101:9001"
    extra_hosts:
      - "authentik.login.no:128.39.142.138"
    environment:
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CORS_ALLOWED_ORIGINS: "https://login.no,https://*.login.no"
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "https://spaces.login.no"
    volumes:
      - rustfs_data:/data
    command:
      - server
      - --address
      - :9000
      - --console-enable
      - --console-address
      - :9001
      - --server-domains
      - s3.login.no
      - /data
    mem_limit: 2g
    cpus: "2.0"

volumes:
  rustfs_data:
